name: challenge
description: Desafio mobile2you.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.2
  flutter_modular: ^4.5.0
  mobx: ^2.0.6+1
  flutter_mobx: ^2.0.4
  dio: ^4.0.5
  dartz: ^0.10.1
  json_annotation: ^4.4.0
  json_serializable: ^6.1.4
  auto_size_text: ^3.0.0
  font_awesome_flutter: ^10.1.0

  
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^1.0.0
  mobx_codegen: ^2.0.5+2  
  build_runner: ^2.1.7

flutter:
  
  uses-material-design: true

  assets:
    - assets/
  

  